name: aur-deploy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: set git cred
        run: |
          git config --global user.email "hey@glenfordwilliams.com"
          git config --global user.name "Glen Will"

      - name: run deploy script
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ./update_packages.sh
